hepsi: derle calistir

derle:
	g++ -I ./include/ -o ./lib/LinkedList.o -c ./src/LinkedList.cpp
	g++ -I ./include/ -o ./lib/LinkedListNode.o -c ./src/LinkedListNode.cpp
	g++ -I ./include/ -o ./bin/test ./lib/LinkedList.o ./lib/LinkedListNode.o ./src/test.cpp
	
calistir:
	./bin/test